title: Services
template: default
layout: layout
mount: 7c3325f3-715c-498f-9724-34f62275161b
revisions: false
route: '/{mount}/{slug}'
sort_dir: asc
date_behavior:
  past: public
  future: private
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
  -
    label: Index
    url: '{mount}'
    refresh: true
structure:
  root: false
  max_depth: 1
