title: Service
tabs:
  main:
    display: 'Main Information'
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              instructions: 'Enter the name of the service. This is a required field and will be prominently displayed throughout the site.'
              display: Name
  sidebar:
    display: 'Related Information'
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              instructions: 'Enter a URL-friendly slug for this service. This will be used in the service’s URL and should be unique. Maximum 200 characters.'
