title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            import: page_header
          -
            handle: layout_modules
            field: common.layout_modules
            config:
              display: Content
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: icon
            field: common.icon
  teaser:
    display: Teaser
    sections:
      -
        fields:
          -
            handle: teaser
            field: common.teaser
  settings:
    display: Settings
    sections:
      -
        display: Settings
        fields:
          -
            handle: enable_cta_box
            field:
              default: true
              type: toggle
              display: 'Enable CTA Box'
              width: 50
          -
            handle: cta_box
            field:
              type: group
              display: 'CTA Box'
              fields:
                -
                  handle: override_defaults
                  field:
                    type: toggle
                    display: 'Override Defaults'
                    width: 50
                -
                  handle: cta_box
                  field: common.cta_box
                  config:
                    if:
                      override_defaults: 'equals true'
