title: Service
tabs:
  main:
    display: 'Main Information'
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
              instructions: 'Enter the name of the service. This is a required field and will be prominently displayed throughout the site.'
              display: Name
          -
            handle: headline
            field: common.headline
            config:
              validate:
                - required
                - 'max:70'
      -
        display: Benefits
      -
        display: Testimonials
  sidebar:
    display: 'Related Information'
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
              instructions: 'Enter a URL-friendly slug for this service. This will be used in the service’s URL and should be unique. Maximum 200 characters.'
          -
            handle: case_studies
            field: common.case_studies
            config:
              display: 'Related Case Studies'
              hide_display: true
          -
            handle: services
            field: common.services
            config:
              display: 'Related Services'
  teaser:
    display: Teaser
    sections:
      -
        display: Teaser
        instructions: 'Create a brief teaser that introduces the case study. This text will be used in overviews to encourage users to click through to the full case study.'
        fields:
          -
            handle: teaser
            field: common.teaser
  cta:
    display: CTA
    sections:
      -
        display: CTA
        fields:
          -
            handle: expert_cta
            field: common.expert_cta
