name: Code Quality Assurance

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  detect_changes:
    name: Detect Changes in Source Files
    runs-on: ubuntu-latest

    outputs:
      php: ${{ steps.filter.outputs.php }}
      js: ${{ steps.filter.outputs.js }}
      ts: ${{ steps.filter.outputs.ts }}
      css: ${{ steps.filter.outputs.css }}
      antlers: ${{ steps.filter.outputs.antlers }}
      dependencies: ${{ steps.filter.outputs.dependencies }}
      changed: ${{ steps.filter.outputs.changed }}

      php_files: ${{ steps.filter.outputs.php_files }}
      js_files: ${{ steps.filter.outputs.js_files }}
      ts_files: ${{ steps.filter.outputs.ts_files }}
      css_files: ${{ steps.filter.outputs.css_files }}
      antlers_files: ${{ steps.filter.outputs.antlers_files }}
      changed_files: ${{ steps.filter.outputs.changed_files }}

    steps:
      - name: Identify Changed Files
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            php:
              - added|modified: '*.php'
            ts:
              - added|modified: '**/*.ts'
            js:
              - added|modified: '**/*.js'
              - added|modified: '**/*.cjs'
              - added|modified: '**/*.mjs'
            css:
              - added|modified: '**/*.css'
            antlers:
              - added|modified: '**/*.antlers.html'
            dependencies:
              - added|modified: 'package.json'
              - added|modified: 'composer.json'
              - added|modified: 'package-lock.json'
              - added|modified: 'composer.lock'
            changed:
              - added|modified: '**/*'
          list-files: shell

  lint_code:
    name: Perform Code Linting
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.changed == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js Environment
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc

      - name: Install Node.js Dependencies
        run: npm ci --prefer-offline

      - name: Check Code Formatting with Prettier
        run: npm run prettier:check ${{ needs.detect_changes.outputs.changed_files }}

      - name: Setup PHP Environment
        if: ${{ needs.detect_changes.outputs.php == 'true' || needs.detect_changes.outputs.dependencies == 'true' }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: dom, curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install Composer Dependencies
        if: ${{ needs.detect_changes.outputs.php == 'true' || needs.detect_changes.outputs.dependencies == 'true' }}
        run: composer install --no-interaction --prefer-dist

      - name: Lint PHP Files
        if: ${{ needs.detect_changes.outputs.php == 'true' || needs.detect_changes.outputs.dependencies == 'true' }}
        run: php vendor/bin/pint --test -v

      - name: Lint TypeScript Files
        if: ${{ needs.detect_changes.outputs.ts == 'true' || needs.detect_changes.outputs.dependencies == 'true' }}
        run: npm run lint:js ${{ needs.detect_changes.outputs.ts_files || '**/*.ts' }}

      - name: Lint JavaScript Files
        if: ${{ needs.detect_changes.outputs.js == 'true' || needs.detect_changes.outputs.dependencies == 'true' }}
        run: npm run lint:js ${{ needs.detect_changes.outputs.js_files || '*.js' }}

      - name: Lint CSS Files
        if: ${{ needs.detect_changes.outputs.css == 'true' || needs.detect_changes.outputs.dependencies == 'true' }}
        run: npm run lint:css ${{ needs.detect_changes.outputs.css_files || '**/*.css' }}

      - name: Build Project
        run: npm run build
