name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run for Semantic Release'
        type: boolean
        required: false
        default: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        with:
          dry_run: ${{ github.event.inputs.dry_run == 'true' || github.event.inputs.dry_run == true }}
