name: Release

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run for Semantic Release'
        type: boolean
        required: false
        default: true

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install Node.js Dependencies
        run: npm ci --prefer-offline

      - name: Semantic Release
        run: npx semantic-release --dry-run=${{ github.event.inputs.dry_run == 'true' || github.event.inputs.dry_run == true }}
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
